default:
    image: docker/compose
    services:
        - docker:dind
    before_script:
        - apk update && apk add git

pipeline:
    stage: build
    script:
        - docker-compose -f docker-compose.yml build mercurios-server mercurios-client || exit 1
        - ./scripts/test.sh || exit 1
        - BRANCH=${CI_COMMIT_BRANCH} ./scripts/dockerhub-push.sh
    artifacts:
        when: always
        paths:
            - mercurios-test-logs
        expire_in: 7 days
