default:
    image: docker/compose
    services:
        - docker:dind
    before_script:
        - apk update && apk add openssh git nodejs npm bash

push:
    script:
        - docker-compose -f docker-compose.yml build mercurios-server mercurios-client || exit 1
        - ./.ops/test.sh
        - BRANCH=${CI_COMMIT_BRANCH} ./.ops/dockerhub-push.sh
    # only:
    #     refs:
    #         - master
    artifacts:
        when: always
        paths:
            - mercurios-test-logs
        expire_in: 7 days
