image: docker

services:
    - docker:dind

before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose

stages:
    - build
    - test

build_server:
    stage: build
    script:
        - ./build.sh
        - ./test.sh
