image: docker

services:
    - docker/compose

# before_script:
#     - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
#     - pip install docker-compose

stages:
    - build
    - test
    - deploy

variables:
    BRANCH: ${CI_COMMIT_BRANCH:-none}

build_server:
    stage: build
    script:
        - ./build.sh
