image: docker/compose

services:
    - docker:dind

before_script:
    - apk add git

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - docker-compose build server client
        - ./scripts/test.sh
        - BRANCH_NAME=${CI_COMMIT_BRANCH} ./scripts/push.sh
