default:
    image: docker/compose
    services:
        - docker:dind
    before_script:
        - apk update && apk add openssh git nodejs npm bash

push:
    script:
        - docker-compose -f docker-compose.yml build mercurios-server mercurios-client || exit 1
        - ./scripts/test.sh
        - ./scripts/dockerhub-push.sh
    only:
        refs:
            - master
    artifacts:
        paths:
            - mercurios-test-logs
        expire_in: 7 days
