default:
    image: docker/compose
    services:
        - docker:dind
    before_script:
        - apk update && apk add openssh git nodejs npm bash

stages:
    - build

push-api:
    stage: build
    script:
        - docker-compose -f docker-compose.yml build mercurios-server mercurios-client || exit 1
        - ./scripts/test.sh || exit 1
        - ./scripts/dockerhub-push.sh || exit 1
    only:
        refs:
            - master
