sudo: required

dist: trusty

services:
    - docker

language: node_js
node_js: 12

before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname
      -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

# before_script:
#     - my_script

script:
    - ./build.sh
    - ./test.sh

# after_script:
#     - my_script

notifications:
    email:
        recipients:
            - simonpiscitelli@gmail.com
        on_success: never # default: change
        on_failure: change # default: always
env:
    global:
        - MY_ENV_VAR=123
