sudo: required

dist: trusty

services:
    - docker

# language: node_js
# node_js: 12

before_install:
    - sudo rm /usr/local/bin/docker-compose
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

# before_script:
#     - my_script

script:
    - ./build.sh

# after_script:
#     - my_script

notifications:
    email:
        recipients:
            - simonpiscitelli@gmail.com
        on_success: never # default: change
        on_failure: change # default: always
# env:
#     global:
#         - MY_ENV_VAR=123
