version: "3.5"

services:
    server:
        image: mercurios_http
        depends_on:
            - postgres
            - nats
        env_file: .env.test
        command: "wait-for-it postgres:5432 -- npm start"

    # mysql:
    #     image: mysql:8
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_ROOT_PASSWORD: secret
    #         MYSQL_DATABASE: mercurios

    postgres:
        image: postgres:11
        env_file: .env.test

    nats:
        image: nats
    # redis:
    #     image: redis:5
