FROM node:lts-alpine
RUN apk add --no-cache python make g++

WORKDIR /app
COPY ./client ./client
COPY ./web ./web

WORKDIR /app/client
RUN npm i
RUN npm run build

WORKDIR /app/web
RUN npm i
RUN npm run build