version: "3.5"

services:
    server:
        image: mercurios_http
        depends_on:
            - postgres
            - nats
        env_file: .env.test
        command: "wait-for-it pg:5432 -- npm start"

    postgres:
        image: postgres:11
        env_file: .env.test

    nats:
        image: nats
