FROM node:lts-alpine
RUN apk add bash

COPY ./scripts/wait-for-it.sh /usr/bin/wait-for-it

WORKDIR /app/client
COPY ./client/package.json ./package.json
COPY ./client/package-lock.json ./package-lock.json
RUN npm install

COPY ./client .
RUN npm run build:clean
