FROM node:lts-slim

RUN apt-get update && apt-get install wait-for-it -y
RUN npm install -g pm2

WORKDIR /app
COPY ./server .

RUN npm ci
RUN npm run build:clean

ENV MERCURIOS_ENV=production

EXPOSE 4254

CMD ["npm", "start"]