FROM node:lts-slim as src
RUN npm i -g pm2
RUN pm2 install typescript
EXPOSE 4254

WORKDIR /app
COPY ./package*.json ./
RUN npm install

WORKDIR /app/playground
COPY ./playground/package*.json ./
RUN npm install

WORKDIR /app
COPY . .
RUN npm run build

WORKDIR /app/playground
RUN npm run build
