FROM node:lts-slim as src
RUN npm i -g pm2
EXPOSE 4254

WORKDIR /app/client
COPY ./client/package*.json ./
RUN npm install

WORKDIR /app/playground
COPY ./playground/package*.json ./
RUN npm install

WORKDIR /app/client
COPY ./client .
RUN npm run build

WORKDIR /app/playground
COPY ./playground .
RUN npm run build
