FROM node:lts-alpine as src
RUN apk add --no-cache python make g++

WORKDIR /app/client
COPY ./client .
RUN npm i
RUN npm run build

WORKDIR /app/web
COPY ./web/package.json .
COPY ./web/package-lock.json .
RUN npm install
COPY ./web .

FROM src as build
RUN npm run build