version: "3.7"

services:
    server:
        image: mercurios_http
        depends_on:
            - mysql
            - nats

    mysql:
        image: mysql:5
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mercurios

    nats:
        image: nats

    test:
        image: mercurios_http
        depends_on:
            - server
        command: sh -c "sleep 10 && npm run test && npm run test:perf"
        environment:
            - TEST_API_URL=http://server:3000
