version: "3.5"

services:
    server:
        user: node
        build: ./server
        image: bahatron/mercurios_http
        volumes:
            - ./server:/app
        ports:
            - 3000:3000
            - 9220:9220
        depends_on:
            - mysql
            - nats
        command: npm run dev
        environment:
            DEBUG: "true"

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mercurios

    nats:
        image: nats
        ports:
            - 4222:4222
            - 8222:8222
