version: "3.5"

services:
    mercurios-playground:
        build:
            context: .
            dockerfile: Dockerfile.playground
        image: mercurios-playground

    mercurios-client:
        build:
            context: .
            dockerfile: Dockerfile.client
        image: mercurios-client
