version: "3.5"

services:
    mercurios-server:
        build:
            context: .
            dockerfile: Dockerfile.server
        image: mercurios-server

    mercurios-client:
        build:
            context: .
            dockerfile: Dockerfile.client
        image: mercurios-client

    mercurios-playground:
        build:
            context: .
            dockerfile: Dockerfile.playground
        image: mercurios-playground
