version: "3.5"

services:
    server:
        image: bahatron/mercurios_http
        depends_on:
            - mysql
            - nats
        env_file: .env.test

    server_tests:
        image: bahatron/mercurios_http
        depends_on:
            - server
        command: sh -c "sleep 5 && npm run test && npm run test:benchmark"
        env_file: .env.test

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mercurios

    nats:
        image: nats
