version: "3.5"

services:
    server:
        image: bahatron/mercurios_http
        volumes:
            - ./server:/app
        ports:
            - ${DOCKER_SERVER_PORT:-3000}:3000
        depends_on:
            - mysql
            - nats
        command: npm run start:dev
        environment:
            - DEBUG=true
        env_file: .env.test

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${DOCKER_MYSQL_PORT:-3306}:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mercurios

    nats:
        image: nats
        ports:
            - ${DOCKER_NATS_SERVER:-4222}:4222
            - ${DOCKER_NATS_STATS:-8222}:8222
