version: "3.5"

x-mercurios-config: &mercurios-config
    MERCURIOS_TEST_URL: http://mercurios-server:4254
    MERCURIOS_WORKERS: 4
    NATS_URL: nats://nats:4222
    # MERCURIOS_DEBUG: 1
    MERCURIOS_DRIVER: pg
    # MERCURIOS_DRIVER: mysql

x-postgres-config: &postgres-config
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: mercurios
    POSTGRES_USER: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: postgres

x-mysql-config: &mysql-config
    MYSQL_USER: admin
    MYSQL_DATABASE: mercurios
    MYSQL_PASSWORD: secret
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_HOST: mysql
    MYSQL_PORT: 3306

services:
    mysql:
        image: mysql:5.6
        # command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        environment:
            <<: *mysql-config

    postgres:
        image: postgres
        container_name: postgres
        environment:
            <<: *postgres-config

    nats:
        image: nats
        container_name: nats

    mercurios-server:
        image: mercurios-server
        container_name: mercurios-server
        command: sh -c "wait-for-it mysql:3306 -- npm start"
        environment:
            <<: *postgres-config
            <<: *mysql-config
            <<: *mercurios-config
        depends_on:
            - postgres
            - mysql
            - nats

    mercurios-client:
        image: mercurios-client
        container_name: mercurios-client
        environment:
            MERCURIOS_URL: http://mercurios-server:4254
