FROM node:lts-alpine as src
RUN apk add bash

WORKDIR /app/client
COPY ./client/package.json ./package.json
COPY ./client/package-lock.json ./package-lock.json
RUN npm install

COPY ./client .
RUN npm run build
