version: "3.5"

x-mercurios-config: &mercurios-config
    NATS_URL: nats://mercurios-nats:4222
    MERCURIOS_TEST_URL: http://mercurios-server:4254
    MERCURIOS_STORE: ${MERCURIOS_STORE:-mysql}
    MERCURIOS_WORKERS: ${MERCURIOS_WORKERS:-2}
    MERCURIOS_DEBUG: 1
    MERCURIOS_DEV: 1
    MERCURIOS_SWAGGER: 1

x-mongo-config: &mongo-config
    MONGO_URL: mongodb://mercurios-mongo:27017/mercurios
    # not necessary if url if mongodb+srv
    MONGO_REPLICA_SET: rs0

x-postgres-config: &postgres-config
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: mercurios
    POSTGRES_USER: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: mercurios-postgres

x-mysql-config: &mysql-config
    MYSQL_USER: admin
    MYSQL_DATABASE: mercurios
    MYSQL_PASSWORD: secret
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_HOST: mercurios-mysql
    MYSQL_PORT: 3306
    # rds ssl cert will be present at /etc/ssl/rds-combined-ca-bundle.pem
    MYSQL_RDS_SSL: 0

# # todo: create store driver
# x-yugabyte-config: &yugabyte-config
#     YUGABYTE_USER: postgres
#     YUGABYTE_DB: postgres
#     YUGABYTE_HOST: mercurios-yb-tserver
#     YUGABYTE_PORT: 5433

services:
    mercurios-server:
        image: mercurios-server
        container_name: mercurios-server
        ports:
            - 4254:4254
            - 9230:9230
        command: sh -c "npm run dev"
        environment:
            <<: *mercurios-config
            <<: *mysql-config
            <<: *postgres-config
            # <<: *yugabyte-config
            <<: *mongo-config

    mercurios-client:
        image: mercurios-client
        container_name: mercurios-client
        command: sh -c "npm run dev"
        volumes:
            - ./client/lib:/app/client/lib
        environment:
            MERCURIOS_URL: ws://mercurios-server:4254
            MERCURIOS_DEV: 1

    mercurios-playground:
        image: mercurios-playground
        container_name: mercurios-playground
        command: sh -c "npm run dev:docker"
        ports:
            - 3000:3000
        environment:
            MERCURIOS_URL: ${MERCURIOS_URL:-http://mercurios-server:4254}

    mercurios-nats:
        image: nats
        container_name: mercurios-nats
        command: ["-V"]
        ports:
            - 4222:4222

    mercurios-mysql:
        image: mysql:5.7
        container_name: mercurios-mysql
        ports:
            - 3306:3306
        environment:
            <<: *mysql-config

    mercurios-postgres:
        image: postgres
        container_name: mercurios-postgres
        ports:
            - 5432:5432
        environment:
            <<: *postgres-config
        command: -c 'max_connections=500'

    mercurios-mongo:
        image: mongo
        container_name: mercurios-mongo
        command: ["--bind_ip_all", "--replSet", "rs0"]
        healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
            interval: 10s
        ports:
            - 27017:27017
