version: "3.5"

x-mercurios-config: &mercurios-config
    MERCURIOS_TEST_URL: http://localhost:4254
    MERCURIOS_WORKERS: 4
    NATS_URL: nats://nats:4222
    MERCURIOS_DEBUG: 1

x-postgres-config: &postgres-config
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: mercurios
    POSTGRES_USER: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: postgres

x-mysql-config: &mysql-config
    MYSQL_USER: admin
    MYSQL_DATABASE: mercurios
    MYSQL_PASSWORD: secret
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_HOST: mysql
    MYSQL_PORT: 3306

x-mongo-config: &mongo-config
    MONGO_URL: mongodb://mercurios-mongo:27017/mercurios
    MONGO_REPLICA_SET: rs0

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            <<: *mysql-config

    postgres:
        image: postgres:12
        container_name: postgres
        environment:
            <<: *postgres-config

    nats:
        image: nats
        container_name: nats

    mongo:
        image: mongo:4.4
        container_name: mongo
        command: ["--bind_ip_all", "--replSet", "rs0"]
        healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
            interval: 10s

    mercurios-client:
        image: mercurios-client
        container_name: mercurios-client
        environment:
            MERCURIOS_URL: ${MERCURIOS_URL:-http://localhost:4254}

    mercurios-mysql-driver:
        image: mercurios-server
        container_name: mercurios-mysql-driver
        command: sh -c "wait-for-it mysql:3306 -- npm start"
        ports:
            - 4254:4254
        environment:
            MERCURIOS_STORE: mysql
            <<: *mysql-config
            <<: *mercurios-config
        depends_on:
            - nats
            - mysql

    mercurios-postgres-driver:
        image: mercurios-server
        container_name: mercurios-postgres-driver
        command: sh -c "wait-for-it postgres:5432 -- npm start"
        environment:
            MERCURIOS_STORE: pg
            <<: *postgres-config
            <<: *mercurios-config
        depends_on:
            - nats
            - postgres

    mercurios-mongo-driver:
        image: mercurios-server
        container_name: mercurios-mongo-driver
        command: sh -c "wait-for-it mongo:27017 -- npm start"
        environment:
            MERCURIOS_STORE: mongo
            <<: *mongo-config
            <<: *mercurios-config
        depends_on:
            - nats
            - mongo
