FROM node:lts-alpine
RUN npm install -g pm2
RUN apk add bash

ARG MERCURIOS_PORT
EXPOSE ${MERCURIOS_PORT:-4254}
ENV MERCURIOS_ENV=production

COPY ./scripts/wait-for-it.sh /usr/bin/wait-for-it

WORKDIR /app/server
COPY ./server/package.json .
COPY ./server/package-lock.json .
RUN npm install

COPY ./server .
RUN npm run build:clean

CMD ["npm", "start"]