version: "3.5"

volumes:
    yb-master-data:
        driver: "local"
    yb-tserver-data:
        driver: "local"

x-mercurios-config: &mercurios-config
    NATS_URL: nats://nats:4222
    # MERCURIOS_PORT: 4254
    MERCURIOS_TEST_URL: http://mercurios-server:4254
    # MERCURIOS_DRIVER: pg
    # MERCURIOS_DRIVER: mysql
    MERCURIOS_WORKERS: 3
    MERCURIOS_DEBUG: 1
    MERCURIOS_ENV: dev

x-postgres-config: &postgres-config
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: mercurios
    POSTGRES_USER: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: postgres

x-mysql-config: &mysql-config
    MYSQL_USER: admin
    MYSQL_DATABASE: mercurios
    MYSQL_PASSWORD: secret
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_HOST: mysql
    MYSQL_PORT: 3306
    # rds ssl cert will be present at /etc/ssl/rds-combined-ca-bundle.pem
    MYSQL_RDS_SSL: 0

# todo: create store driver
x-yugabyte-config: &yugabyte-config
    YUGABYTE_USER: postgres
    YUGABYTE_DB: postgres
    YUGABYTE_HOST: yb-tserver
    YUGABYTE_PORT: 5433

services:
    yb-master:
        image: yugabytedb/yugabyte:latest
        container_name: yb-master
        volumes:
            - yb-master-data:/mnt/master
        command:
            [
                "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master:7100",
                "--rpc_bind_addresses=yb-master:7100",
                "--replication_factor=1",
            ]
        ports:
            - "7000:7000"
        environment:
            SERVICE_7000_NAME: yb-master

    yb-tserver:
        image: yugabytedb/yugabyte:latest
        container_name: yb-tserver
        volumes:
            - yb-tserver-data:/mnt/tserver
        command:
            [
                "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=yb-tserver:9100",
                "--tserver_master_addrs=yb-master:7100",
            ]
        ports:
            - "9042:9042"
            - "5433:5433"
            - "9000:9000"
        environment:
            SERVICE_5433_NAME: ysql
            SERVICE_9042_NAME: ycql
            SERVICE_6379_NAME: yedis
            SERVICE_9000_NAME: yb-tserver
        depends_on:
            - yb-master

    mysql:
        image: mysql:5.6
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            <<: *mysql-config
        # command: --default-authentication-plugin=mysql_native_password

    postgres:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            <<: *postgres-config
        command: -c 'max_connections=500'

    nats:
        image: nats
        container_name: nats
        command: ["-V", "-m=8222"]
        ports:
            - 4222:4222
            - 8222:8222

    mercurios-server:
        image: mercurios-server
        container_name: mercurios-server
        ports:
            - 4254:4254
            - 9230:9230
        command: sh -c "wait-for-it mysql:3306 -s -t 30 -- npm run dev"
        environment:
            <<: *mercurios-config
            <<: *mysql-config
            <<: *postgres-config
            <<: *yugabyte-config

    mercurios-client:
        image: mercurios-client
        container_name: mercurios-client
        command: sh -c "npm run dev"
        volumes:
            - ./client/lib:/app/client/lib
        environment:
            MERCURIOS_URL: http://mercurios-server:4254
            MERCURIOS_ENV: dev

    mercurios-playground:
        image: mercurios-playground
        container_name: mercurios-playground
        command: sh -c "wait-for-it mercurios-server:4254 -- npm run dev:docker"
        ports:
            - 8080:8080
            - 8081:8081
        environment:
            VUE_APP_MERCURIOS_URL: http://localhost:4254
