version: "3.5"

x-mercurios-config: &mercurios-config
    MERCURIOS_PORT: 4254
    # MERCURIOS_DEBUG: 1
    #  max
    MERCURIOS_WORKERS: 4
    MERCURIOS_TEST_URL: http://mercurios-server:4254
    NATS_URL: nats://mercurios-nats:4222
    MERCURIOS_DRIVER: pg
    # MERCURIOS_DRIVER: mysql

x-postgres-config: &postgres-config
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: mercurios
    POSTGRES_USER: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: mercurios-postgres

x-mysql-config: &mysql-config
    MYSQL_USER: admin
    MYSQL_DATABASE: mercurios
    MYSQL_PASSWORD: secret
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_HOST: mercurios-mysql
    MYSQL_PORT: 3306

services:
    mercurios-mysql:
        image: mysql:5.6
        # command: --default-authentication-plugin=mysql_native_password
        container_name: mercurios-mysql
        environment:
            <<: *mysql-config

    mercurios-postgres:
        image: postgres
        container_name: mercurios-postgres
        environment:
            <<: *postgres-config

    mercurios-nats:
        image: nats
        container_name: mercurios-nats

    mercurios-server:
        image: mercurios-server
        container_name: mercurios-server
        command: sh -c "wait-for-it mercurios-mysql:3306 -- npm run migrate && npm start"
        environment:
            <<: *postgres-config
            <<: *mysql-config
            <<: *mercurios-config
        depends_on:
            - mercurios-postgres
            - mercurios-mysql
            - mercurios-nats

    mercurios-client:
        image: mercurios-client
        container_name: mercurios-client
        environment:
            MERCURIOS_URL: http://mercurios-server:4254
