version: "3.5"

services:
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mercurios

    redis:
        image: redis:5

    nats:
        image: nats
        command: ["-V"]
        ports:
            - 8222:8222

    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        image: mercurios_http
        volumes:
            - ./server:/app
        ports:
            - ${MERCURIOS_PORT:-4254}:${MERCURIOS_PORT:-4254}
        depends_on:
            - mysql
            - nats
        command: sh -c "wait-for-it mysql:3306 -s -t 30 -- npm run build:clean && npm run dev"
        # command: npm run dev
        environment:
            - NODE_ENV=dev
        env_file: .env.test

    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        image: mercurios_admin
        volumes:
            - ./web:/app/web
        command: npm run dev
        ports:
            - 3100:3000

    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        env_file: .env.test
        volumes:
            - ./client:/app
        command: npm run dev
