FROM node:lts-slim as src
COPY scripts/wait-for-it.sh /usr/bin/wait-for-it
RUN chmod 777 /usr/bin/wait-for-it
RUN npm i -g pm2
EXPOSE 4254

WORKDIR /app/client
COPY ./client/package*.json ./
RUN npm install

WORKDIR /app/playground
COPY ./playground/package*.json ./
RUN npm install

WORKDIR /app/client
COPY ./client .
RUN npm run prepare

WORKDIR /app/playground
COPY ./playground .
RUN npm run build
CMD [ "npm", "run", "dev" ]