version: "3.5"

services:
    server:
        image: bahatron/mercurios_http
        depends_on:
            - mysql
            - nats
        env_file: .env.test

    tests:
        image: mercurios_tests
        depends_on:
            - server
        env_file: .env.test
        command: sh -c "sleep 5 && npm start"

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mercurios

    nats:
        image: nats
