version: "3.5"

x-client-config: &client-config
    MERCURIOS_TEST_URL: postgres://admin:secret@mercurios-postgres:5432/postgres
    MERCURIOS_DEV: 1

x-postgres-config: &postgres-config
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: postgres
    POSTGRES_USER: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: mercurios-postgres

services:
    mercurios-postgres:
        image: postgres
        container_name: mercurios-postgres
        ports:
            - 5432:5432
        environment:
            <<: *postgres-config
        command: -c 'max_connections=500'

    mercurios-playground:
        build:
            context: .
            dockerfile: Dockerfile.playground
        image: mercurios-playground
        ports:
            - 4254:4254
        container_name: mercurios-playground
        command: npm run pm2
        environment:
            <<: *client-config
        depends_on:
            - mercurios-postgres
