version: "3.7"

services:
    server:
        image: bahatron/mercurios_http
        depends_on:
            - mysql
            - nats
        environment:
            DEBUG: "false"

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mercurios

    nats:
        image: nats

    test:
        image: bahatron/mercurios_http
        depends_on:
            - server
        command: sh -c "sleep 5 && npm run test && npm run test:perf"
        environment:
            - TEST_SERVER_URL=http://server:3000
