version: "3.5"

volumes:
    mercurios-yb-master-data:
        driver: "local"
    mercurios-yb-tserver-data:
        driver: "local"

# todo: create store driver
x-yugabyte-config: &yugabyte-config
    YUGABYTE_USER: postgres
    YUGABYTE_DB: postgres
    YUGABYTE_HOST: mercurios-yb-tserver
    YUGABYTE_PORT: 5433

services:
    mercurios-yb-master:
        image: yugabytedb/yugabyte:latest
        container_name: mercurios-yb-master
        volumes:
            - mercurios-yb-master-data:/mnt/master
        command:
            [
                "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=mercurios-yb-master:7100",
                "--rpc_bind_addresses=mercurios-yb-master:7100",
                "--replication_factor=1",
            ]
        ports:
            - "7000:7000"
        environment:
            SERVICE_7000_NAME: mercurios-yb-master

    mercurios-yb-tserver:
        image: yugabytedb/yugabyte:latest
        container_name: mercurios-yb-tserver
        volumes:
            - mercurios-yb-tserver-data:/mnt/tserver
        command:
            [
                "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=mercurios-yb-tserver:9100",
                "--tserver_master_addrs=mercurios-yb-master:7100",
            ]
        ports:
            - "9042:9042"
            - "5433:5433"
            - "9000:9000"
        environment:
            SERVICE_5433_NAME: ysql
            SERVICE_9042_NAME: ycql
            SERVICE_6379_NAME: yedis
            SERVICE_9000_NAME: mercurios-yb-tserver
        depends_on:
            - mercurios-yb-master
