version: "3.5"

x-mercurios-config: &mercurios-config
    MERCURIOS_PORT: 4254
    # MERCURIOS_DEBUG: 1
    #  max
    MERCURIOS_WORKERS: 4
    MERCURIOS_TEST_URL: http://mercurios_server:4254
    NATS_URL: nats://mercurios_nats:4222
    MERCURIOS_DRIVER: pg
    # MERCURIOS_DRIVER: mysql

x-postgres-config: &postgres-config
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: mercurios
    POSTGRES_USER: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: mercurios_postgres

x-mysql-config: &mysql-config
    MYSQL_USER: admin
    MYSQL_DATABASE: mercurios
    MYSQL_PASSWORD: secret
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_HOST: mercurios_mysql
    MYSQL_PORT: 3306

services:
    mercurios_mysql:
        image: mysql:5.6
        # command: --default-authentication-plugin=mysql_native_password
        container_name: mercurios_mysql
        environment:
            <<: *mysql-config

    mercurios_postgres:
        image: postgres
        container_name: mercurios_postgres
        environment:
            <<: *postgres-config

    mercurios_nats:
        image: nats
        container_name: mercurios_nats

    mercurios_server:
        image: mercurios_server
        container_name: mercurios_server
        command: sh -c "wait-for-it mercurios_mysql:3306 -- npm run migrate && npm start"
        environment:
            <<: *postgres-config
            <<: *mysql-config
            <<: *mercurios-config
        depends_on:
            - mercurios_postgres
            - mercurios_mysql
            - mercurios_nats

    mercurios_client:
        image: mercurios_client
        container_name: mercurios_client
        environment:
            MERCURIOS_URL: http://mercurios_server:4254
