version: "3.5"

x-client-config: &client-config
    NATS_URL: nats://mercurios-nats:4222
    MERCURIOS_STORE: ${MERCURIOS_STORE:-pg}
    MERCURIOS_WORKERS: ${MERCURIOS_WORKERS:-2}
    MERCURIOS_DEBUG: 1
    MERCURIOS_DEV: 1
    MERCURIOS_SWAGGER: 1

x-mongo-config: &mongo-config
    MONGO_URL: mongodb://mercurios-mongo:27017/mercurios?replicaSet=rs0

## TODO: CONVERT TO SINGLE LINE URL
x-postgres-config: &postgres-config
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: mercurios
    POSTGRES_USER: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: mercurios-postgres

services:
    mercurios-postgres:
        image: postgres
        container_name: mercurios-postgres
        ports:
            - 5432:5432
        environment:
            <<: *postgres-config
        command: -c 'max_connections=500'

    mercurios-mongo:
        image: mongo
        container_name: mercurios-mongo
        command: /scripts/mongo-init.sh
        working_dir: /scripts
        volumes:
            - ./scripts:/scripts
        ports:
            - 27017:27017
        environment:
            MONGO_DB_REPLICA_SET_NAME: rs0
            MONGO_DB_HOST_NAME: io-mongo
            MONGO_DB_HOST_PORT: 27017

    mercurios-playground:
        image: mercurios-playground
        container_name: mercurios-playground
        command: sh -c "npm run dev"
        environment:
            <<: *client-config
            <<: *postgres-config
            <<: *mongo-config
        ports:
            - 4254:4254
        depends_on:
            - mercurios-postgres
            - mercurios-mongo

    mercurios-client:
        image: mercurios-client
        container_name: mercurios-client
        command: sh -c "npm run build:watch"
        environment:
            <<: *client-config
            <<: *postgres-config
            <<: *mongo-config
        depends_on:
            - mercurios-playground
        volumes:
            - ./client/lib:/app/client/lib
