version: "3.5"

services:
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${DOCKER_MYSQL_PORT:-3306}:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mercurios

    nats:
        image: nats
        ports:
            - ${DOCKER_NATS_SERVER:-4222}:4222
            - ${DOCKER_NATS_STATS:-8222}:8222

    server:
        image: bahatron/mercurios_http
        volumes:
            - ./server:/app
        ports:
            - ${MERCURIOS_PORT}:${MERCURIOS_PORT}
        depends_on:
            - mysql
            - nats
        command: sh -c "npm run build:clean && npm run dev"
        environment:
            - DEBUG=true
        env_file: .env

    web:
        user: node
        image: bahatron/mercurios_admin
        volumes:
            - ./web:/app
        command: npm run dev
        ports:
            - 3100:3000
